sudo: required
services:
  - docker

before_install:
  - docker build -t lexworks/docker-react -f Dockerfile.dev .

script:
  - docker run lexworks/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "bdoreactapp-melvin"
  env: "BdoreactappMelvin-env"
  bucket_name: "elasticbeanstalk-us-east-2-792844797253"
  bucket_path: "bdoreactapp-melvin"
  on:
    branch: master
  access_key_id: "AKIAJBMEJAOVZ4U6GUTA" 
  secret_access_key:
    secure: "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"

